providers: []
roleSets: 
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: EC2-Default-SSM-AD-Role
        instanceProfile: true
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundaryPolicy: AWSAccelerator-Default-Boundary-Policy
policySets: []
groupSets: 
  - deploymentTargets:
      organizationalUnits:
        - Root
    groups:
      - name: Administrators
        policies:
          awsManaged:
            - AdministratorAccess
userSets: 
  - deploymentTargets:
      accounts:
        - Management
    users:
      - username: breakGlassUser01
        group: Administrators
identityCenter:
  name: IdentityCenter
  delegatedAdminAccount: Audit
  identityCenterPermissionSets:
    - name: prodam-sso-administrator
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: prodam-sso-billing
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/Billing
      sessionDuration: 60
    - name: prodam-sso-securityaudit
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/SecurityAudit
          - arn:aws:iam::aws:policy/AmazonDetectiveFullAccess
          - arn:aws:iam::aws:policy/AWSSSOMemberAccountAdministrator
          - arn:aws:iam::aws:policy/job-function/SupportUser
      sessionDuration: 60
    - name: prodam-sso-securityresponse
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: prodam-sso-network-admin
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/NetworkAdministrator
      sessionDuration: 60
    - name: prodam-sso-db-management
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
      sessionDuration: 60
    - name: prodam-sso-app-monitoring
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/SupportUser
    - name: prodam-sso-app-billing
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/Billing
      sessionDuration: 60
    - name: AccPermissionSet-AdministratorAccessGlobal
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: AccPermissionSet-AdministratorAccessSmartCore 
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: AccPermissionSet-AdministratorAccessSmartIOT
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: AccPermissionSet-AdministratorAccessSmartGPS
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
    - name: AccPermissionSet-AdministratorAccessSmartNeo
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60

    # Power User Permission Sets
    - name: AccPermissionSet-PowerUserAccessGlobal
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60
    - name: AccPermissionSet-PowerUserAccessSmartCore 
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60
    - name: AccPermissionSet-PowerUserAccessSmartIOT
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60
    - name: AccPermissionSet-PowerUserAccessSmartGPS
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60
    - name: AccPermissionSet-PowerUserAccessSmartNeo 
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60 

    # Permission set by roles
    - name: AccPermissionSet-Security-engineer
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/SecurityAudit
          - arn:aws:iam::aws:policy/AWSSSOMemberAccountAdministrator
      sessionDuration: 60
    - name: AccPermissionSet-Network-engineer
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/NetworkAdministrator
      sessionDuration: 60
    - name: AccPermissionSet-ReadOnlyAccess 
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
      sessionDuration: 60  
    - name: AccPermissionSet-Viewonly
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
      sessionDuration: 60  
    - name: AccPermissionSet-Billing
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/job-function/Billing
      sessionDuration: 60  
    - name: AccPermissionSet-monitoring-readonly
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/AWSGrafanaConsoleReadOnlyAccess
      sessionDuration: 60 
    - name: AccPermissionSet-monitoring-engineer
      policies: 
        awsManaged:
          - arn:aws:iam::aws:policy/AWSGrafanaAccountAdministrator
          - arn:aws:iam::aws:policy/AmazonPrometheusFullAccess
      sessionDuration: 60 

    # Permission sets  to Workloads Accounts Developers 
    - name: AccPermissionSet-developerSmartCore  
      policies: 
        inlinePolicy: iam-policies/developers-inline-policy.json
      sessionDuration: 60 
    - name: AccPermissionSet-developerSmartIOT  
      policies: 
        inlinePolicy: iam-policies/developers-inline-policy.json
      sessionDuration: 60 
    - name: AccPermissionSet-developerSmartGPS  
      policies: 
        inlinePolicy: iam-policies/developers-inline-policy.json
      sessionDuration: 60 
    - name: AccPermissionSet-tech-leadSmartNeo 
      policies: 
        inlinePolicy: iam-policies/developers-inline-policy.json
      sessionDuration: 60 

    # Permission sets  to Workloads Accounts tech Leads
    - name: AccPermissionSet-tech-leadSmartCore
      policies: 
        inlinePolicy: iam-policies/tech-leads-inline-policy.json
      sessionDuration: 60 
    - name: AccPermissionSet-tech-leadSmartIOT
      policies: 
        inlinePolicy: iam-policies/tech-leads-inline-policy.json
      sessionDuration: 60  
    - name: AccPermissionSet-tech-leadSmartGPS
      policies: 
        inlinePolicy: iam-policies/tech-leads-inline-policy.json
      sessionDuration: 60 
    - name: AccPermissionSet-tech-leadSmartNeo
      policies: 
        inlinePolicy: iam-policies/tech-leads-inline-policy.json
      sessionDuration: 60 
